# Module: networking
# VPC, subnets, internet gateway, NAT, security groups, route tables
# Generated by arch2terraform — do not edit manually

# From diagram node: Main VPC (low-confidence match, confidence=0.90 — please review)
resource "aws_vpc" "main_vpc" {
  cidr_block = var.cidr_block

  tags = merge(var.common_tags, {
    Name        = "Main VPC"
    Module      = "aws_vpc"
  })
}
