# Module: database
# RDS, DynamoDB, ElastiCache, OpenSearch
# Generated by arch2terraform — do not edit manually

# From diagram node: PostgreSQL DB (low-confidence match, confidence=0.85 — please review)
resource "aws_db_instance" "postgres_db" {
  engine            = "postgres"
  instance_class    = "db.t3.micro"
  engine_version    = "15"
  allocated_storage = "20"
  multi_az          = "false"

  tags = merge(var.common_tags, {
    Name        = "PostgreSQL DB"
    Module      = "aws_db_instance"
  })
}
