# Root module — generated by arch2terraform
# This file wires all child modules together.

provider "aws" {
  region = var.aws_region
}

module "networking" {
  source = "./modules/networking"

  aws_region  = var.aws_region
  environment = var.environment
  project     = var.project
  common_tags = local.common_tags
}

module "database" {
  source = "./modules/database"

  aws_region  = var.aws_region
  environment = var.environment
  project     = var.project
  common_tags = local.common_tags
}

module "compute" {
  source = "./modules/compute"

  aws_region  = var.aws_region
  environment = var.environment
  project     = var.project
  common_tags = local.common_tags
}
