# Module: database
# RDS, DynamoDB, ElastiCache, OpenSearch
# Generated by arch2terraform — do not edit manually

# From diagram node: PostgreSQL DB (low-confidence match, confidence=0.85 — please review)
resource "aws_db_instance" "postgres_db" {
  engine            = var.engine
  instance_class    = var.instance_class
  engine_version    = var.engine_version
  allocated_storage = var.allocated_storage
  multi_az          = var.multi_az

  tags = merge(var.common_tags, {
    Name        = "PostgreSQL DB"
    Module      = "aws_db_instance"
  })
}
