# Module: compute
# EC2 instances, auto scaling groups, load balancers
# Generated by arch2terraform — do not edit manually

# From diagram node: Web Server (low-confidence match, confidence=0.80 — please review)
resource "aws_instance" "web_server" {
  instance_type = var.instance_type
  ami           = var.ami

  tags = merge(var.common_tags, {
    Name        = "Web Server"
    Module      = "aws_instance"
  })
}
